### ISSUE TITLE
matlab plotly api version number updated

### ISSUE THREAD

**Issue by imatlab-helper** [imatlab/imatlab#17]
My PR for updating the plotly version number has succeeded. They're now at 2.2.7

**Comment by anntzer** [comment]
Added a version check during `imatlab_export_fig('fig2plotly')`.

**Comment by anntzer** [comment]
@imatlab-helper closing under the assumption that the version check works for you but let me know if it doesn't.

**Comment by imatlab-helper** [comment]
I sadly haven't had time to test this yet, but will reply to this thread if it doesn't.

**Comment by imatlab-helper** [comment]
I finally got around to testing this. The version check does work.
However, I have a new problem with inline graphics that is preventing plotting in plotly that I'll post a new issue on (or follow-up on the other inline graphics thread).
