### ISSUE TITLE
plotly plotting fails, has an escaped character warning 

### ISSUE THREAD

**Issue by imatlab-helper** [imatlab/imatlab#18]
This is new behavior for me. I updated matlab plotly to the latest git version, updated the js bundle, and am using the latest git version of imatlab.

```
Warning: Escaped character '\(' is not valid. See 'doc sprintf' for supported special characters.
> In plotlyoffline (line 78)
  In plotlyfig/plotly (line 445)
  In fig2plotly (line 49)
  In imatlab_export_fig (line 47)
```

After digging around, the error was traced to the javascript bundle, and presumably some other change (or lack of change since the plotly js has been updated) with the plotly code that I have not figured out yet.

What will work: the plotly js bundle version 1.24.0 (just happened to be the version I had installed at that time). The current version (1.26.1) will not work and causes the error seen above.

Also, I think this is a new error, but plotly plots no longer work on the latest version of firefox shipped with xenial (53.0), but are fine on firefox 50.1.0 on a Mac. Chrome works fine.

**Comment by anntzer** [comment]
Is there anything that can even be done on imatlab's side?  I don't even know if you can specifically download a given version of the js bundle, or check the version of that bundle.
If yes we could document the required versions; otherwise I'll just pull out the standard "not my fault" response :-/ (Sorry, but I really have no interest chasing down plotly's own issues).

**Comment by imatlab-helper** [comment]
I agree, there's nothing I was proposing we do about it (or really could do about it). However our current instructions lead to a broken system, sigh.
As a mitigation strategy until plotly fixes things, we can point people to at least one version that I know is working: https://cdn.plot.ly/plotly-1.24.0.min.js instead of plotly-latest.min.js

**Comment by anntzer** [comment]
Please do open a PR with the new URL (perhaps with a note explaining the issue).

**Comment by imatlab-helper** [comment]
Well, now I'm totally confused. I just pulled every version of plotly all the way back to 1.24.0, and even that shows the same error. However, being the paranoid person that I am, I kept my original 1.24.0 back from early March, and that one still works. The md5sums don't match between the 1.24.0 that I downloaded back in March and the one I pulled just now. This is frustrating because now I have no good URL to point to. Blah.

**Comment by imatlab-helper** [comment]
Digging through getplotlyoffline shows that there is an "escapechars" call that happens to the bundle...yikes. That must be it.

**Comment by imatlab-helper** [comment]
Yup, that was it. Direct downloads of the js bundle (which is what I just did) must be escaped first. Replace all `\` with `\\` and all `%` with `%%`.
I have a non-standard install location of the bundle (single location for the system instead of per user), so the getplotlyoffline script doesn't work out of the box for me. It hadn't occurred to me that it would have to be tweaked. lesson learned.
