### ISSUE TITLE
getplotlyoffline reported a ssl error

### ISSUE THREAD

**Issue by Harlan-pku** [imatlab/imatlab#19]
Thank you for the awesome project but when I followed the instructions in README.rst to  install Plotly MATLAB API, I got an error in MATLAB:

```
Response stream is undefined
 below is a Java Error dump (truncated):
error using urlread2 (line 217)
Java exception occurred:
javax.net.ssl.SSLException: Received fatal alert: protocol_version
```

I seems that the ssl protocol version of plotly website is not suitable with MATLAB. So I think it's better to use http instead of https in the url.

**Comment by anntzer** [comment]
Edited readme, thanks for the notice.
