### ISSUE TITLE
Size of exported figures is not same as display figures.

### ISSUE THREAD

**Issue by Harlan-pku** [imatlab/imatlab#20]
I am trying to use ```imatlab_export_fig('print-png')``` to export my figure, but the size of exported picture is not same as display figure. I used ```set(gcf,'Position',[50 50 600,400])``` to set my fig as size of 400x400, but I got a 625x625 picture. I tested print function in MATLAB (R2017a) and I found that an ```-r0``` parameter should be added to print function to make these two figures same, like this: ```print('PeaksSurface','-dpng','-r0')```

**Comment by anntzer** [comment]
Sounds reasonable, fixed to use -r0 ("export using screen resolution") by default.
