### ISSUE TITLE
Hi, I get this error whenever I try to execute. Please suggest. >> getplotlyoffline('http://cdn.plot.ly/plotly-latest.min.js')

### ISSUE THREAD

**Issue by sainag2473** [imatlab/imatlab#23]
>> getplotlyoffline('http://cdn.plot.ly/plotly-latest.min.js')
Error using validatedir (line 5)
Error saving plotlyjs folder: Permission denied, MATLAB:MKDIR:OSError. Please contact
support@plot.ly for assistance.

Error in getplotlyoffline (line 23)
   validatedir(status, mess, messid, 'plotlyjs');

**Comment by anntzer** [comment]
As the error message states, this is a plotly error.  Please file the issue with them.

**Comment by sainag2473** [comment]
Sure, Thanks.
