### ISSUE TITLE
JavaScript issue with plotly inline graphics

### ISSUE THREAD

**Issue by mvdm** [imatlab/imatlab#24]
When using the `fig2plotly` output option as described in the readme, any MATLAB plotting command in my Jupyter notebook gives the following error for me:

```
Drawing...
(no image displayed)
Javascript error adding output!
ReferenceError: Plotly is not defined
See your browser Javascript console for more details.
```

The following DO work:

- inline graphics with the other options (jpeg, png)
- inline plotly graphics generated using Jupyter and Python 3.5
- plotly offline html output directly from MATLAB, as follows:
```
>> imatlab_export_fig('fig2plotly')
>> imagesc(rand(10))
>> imatlab_export_fig
```

Trying different browsers (Chrome, Firefox, IE) made no difference. Any ideas?

(Thanks @anntzer for the nice package!)

**Comment by anntzer** [comment]
Is it the issue mentioned (with a workaround) here? https://github.com/imatlab/imatlab/issues/2#issuecomment-294107129
Apparently notebook 5.1 will be released "soon" with this fix.

Once 5.1 is out I think we should add a fix at https://github.com/imatlab/imatlab/blob/master/imatlab/_kernel.py#L238 that reports an error if `notebook.__version__ == 5.0.0`.

**Comment by mvdm** [comment]
I never saw the data rate error mentioned in #2, but upgraded to the current notebook build anyway (`pip install -U git+https://github.com/jupyter/notebook`). This fixed the issue: plotly graphics now display inline correctly. Thanks for the pointer!

**Comment by anntzer** [comment]
I suspect that you have some setting that hides the warning.  Keeping the issue open as a reminder for the need for the check mentioned above.

**Comment by anntzer** [comment]
notebook 5.1 was recently released, so I pushed the commit blacklisting jupyter 5.0.
Please confirm that it works for you.
