### ISSUE TITLE
fig2plotly plotting fails with Javascript ReferenceError

### ISSUE THREAD

**Issue by imatlab-helper** [imatlab/imatlab#28]
I don't know when this problem cropped up, but I can confirm that plotting with ```print-png``` works just fine, but ```fig2plotly``` plotting does not. The environment that is broken (a fresh install) uses:
```
ipython==6.2.0
jupyter-core==4.3.0
jupyter-client==5.1.0
jupyter-console==5.2.0
matlab 2017a
```
An older environment that does work is with the following:
```
ipython==5.3.0
jupyter-core==4.3.0
jupyter-client==5.0.1
jupyter-console==5.1.0
matlab 2016b
```

fig2plotly plotting attempt fails with a ```Drawing...``` message at the top of the output of the cell and the bottom of the cell outputs three lines:
```
Javascript error adding output!
ReferenceError: Plotly is not defined
See your browser Javascript console for more details.
```
![170922_imatlab_error](https://user-images.githubusercontent.com/26192908/30761812-852d48e2-9f94-11e7-9503-7c165ce373c2.png)

The Javascript console reports:
```
outputarea.js:456 ReferenceError: Plotly is not defined
    at eval (eval at globalEval (jquery.min.js:4), <anonymous>:1:85)
    at eval (<anonymous>)
    at Function.globalEval (jquery.min.js:4)
    at init.domManip (jquery.min.js:5)
    at init.append (jquery.min.js:5)
    at OutputArea._safe_append (outputarea.js:453)
    at OutputArea.append_display_data (outputarea.js:652)
    at OutputArea.append_output (outputarea.js:343)
    at OutputArea.handle_output (outputarea.js:254)
    at output (codecell.js:376)
OutputArea._safe_append	@	outputarea.js:456
OutputArea.append_display_data	@	outputarea.js:652
OutputArea.append_output	@	outputarea.js:343
OutputArea.handle_output	@	outputarea.js:254
output	@	codecell.js:376
Kernel._handle_output_message	@	kernel.js:1196
i	@	jquery.min.js:4
Kernel._handle_iopub_message	@	kernel.js:1223
Kernel._finish_ws_message	@	kernel.js:1015
(anonymous)	@	kernel.js:1006
```

Any thoughts on where the issue could be?

**Comment by anntzer** [comment]
Indeed.  This bisects back to https://github.com/ipython/ipython/pull/10634/files#diff-669aef382d43ba6b34e0347434278127L284 (commenting out the check fixes the issue).  `display` is called directly by `plotly`'s `init_notebook_mode`.  Looks like we need to either fake-init an InteractiveShell (beh), or locally patch `display` with a copy-paste of the old version (see our own `_plotly_init_notebook_mode`).  Not sure I have any better idea right now.

**Comment by imatlab-helper** [comment]
You're right, commenting out lines [271-274](https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L271) of display.py makes this problem go away.

Do we declare that we're using a non-interactive shell at some point?

For the second approach, is there a place where we're calling display that we can overwrite with our custom display function?

**Comment by anntzer** [comment]
We never instantiate an InteractiveShell, and it seems a bit silly to instantiate one just to work around the new behavior (given that I don't think we're really using the ipykernel machinery in a standard way anyways so it'll just break again the next time they decide to change the precise semantics).

We already do some patching in https://github.com/imatlab/imatlab/blob/master/imatlab/_kernel.py#L274, I think it'd be good enough to copy-paste the old definition of display and monkeypatch it there (and then we can inline the patching of publish_display_data).

**Comment by imatlab-helper** [comment]
Thanks, I think I understand (in principle) how this would happen. I sadly don't have the time to work on a solution at the moment, but potentially in the coming weeks.

**Comment by anntzer** [comment]
I pushed the fix, but let me know if any issue remains.
