### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by atom77** [imatlab/imatlab#33]
I'm getting following error “_ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /app/Applications/MATLAB/R2017a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libmx.so)_
“
during kernel installation step. it seems it is unagble to load matlab.engine.

```
/app/Applications/Python-3.5.2/Build/bin/python3.5   -mimatlab install
Traceback (most recent call last):
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/site-packages/matlab/engine/__init__.py", line 42, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'matlabengineforpython3_5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/site-packages/matlab/engine/__init__.py", line 58, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /app/Applications/MATLAB/R2017a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libmx.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/site-packages/imatlab/__main__.py", line 3, in <module>
    from ._kernel import MatlabKernel
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/site-packages/imatlab/_kernel.py", line 19, in <module>
    import matlab.engine
  File "/app/Applications/Python-3.5.2/Build/lib/python3.5/site-packages/matlab/engine/__init__.py", line 61, in <module>
    'MathWorks Technical Support for assistance: %s' % e)
OSError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /app/Applications/MATLAB/R2017a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libmx.so)
```

However, I can load matlab.engine inside the python3.5 with no errors

```
/app/Applications/Python-3.5.2/Build/bin/python3.5   
Python 3.5.2 (default, Nov 18 2016, 18:23:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matlab.engine
>>> 

```
What could be the reason? Many thanks.

**Comment by anntzer** [comment]
Can you try inverting the import of plotly and the import of matlab.engine in _kernel.py?

**Comment by imatlab-helper** [comment]
This looks like another "matlab using an old library" error for the wrong version of `libstdc++`, but the weird thing is that it's pulling the system version in `/usr/lib64`.
The problem appears identical to this:
https://www.mathworks.com/matlabcentral/answers/329796-issue-with-libstdc-so-6
except there the issue was from clearly using the matlab version.

Is this Redhat/Centos? What is the output of `gcc -v`?
Maybe the problem is that Centos's gcc is old, and that r2017a's `libmx` expects a more recent version with `CXXABI_1.3.8` extensions. If so, that would mean that we should not be specifying the system `libstdc++` to use with `LD_LIBRARY_PATH` for systems with old versions of gcc?

**Comment by rkdarst** [comment]
For others who are reading: my solution within jupyter, implementing the solution in the link above: add the following line to the kernelspec (choose your proper system/conda environment libstdc++)

```
    "env": {"LD_PRELOAD": "/share/apps/jupyterhub/live/miniconda/lib/libstdc++.so" }
```

Kernelspec is in your prefix's `share/jupyter/kernels/matlab/kernel.json` or `~/.local/share/jupyter/kernels/matlab/kernel.json`.

**Comment by RoyiAvital** [comment]
@anntzer , Could one have 2 MATLAB Kernels in parallel?

Thank You.

**Comment by anntzer** [comment]
dunno, did you try? :)

**Comment by anntzer** [comment]
@atom77 Can you try the solution at https://github.com/imatlab/imatlab/issues/33#issuecomment-357101465?  If that works, I think I have a "reasonable" solution...

**Comment by RoyiAvital** [comment]
@anntzer ,
I tried.
Both `imatlab` and `matlab_kernel` can work together as you call yours as MATLAB and they use Matlab.

**Comment by rkdarst** [comment]
Interestingly, I just tried reinstalling everything from scratch, and `imatlab` just works without this work-around.  Before, I made a mistake and was using `matlab_kernel` when I thought it was this one.  Still, the answer should be the same for both I guess.

Likely this is irrelevant to others, but the following (makefile) stipend uses the `jq` program to automatically fix the `kernel.json` file, so I can deploy automatically.  edit for your environment:
```
        cat $(KERNEL_PREFIX)/share/jupyter/kernels/matlab/kernel.json | jq "setpath ([\"env\"]; {LD_PRELOAD: \"$$PWD/miniconda/lib/libstdc++.so\" \})" > $(KERNEL_PREFIX)/share/jupyter/kernels/matlab/kernel.json.new
        mv $(KERNEL_PREFIX)/share/jupyter/kernels/matlab/kernel.json{.new,} 
```

I also install them along side each other.  For each kernel, you can give it a name(identifier) to install as, and as long as the names are unique you can have the same kernel.  These two kernel have different default names, so it's easy.  Check the `install` subcommand help text for options on changing the names.

**Comment by anntzer** [comment]
The patch I'm proposing is basically
```
+# Work around LD_PRELOAD tricks played by MATLAB by looking for a working
+# import order.
+if subprocess.call(
+        [sys.executable, "-c", "import plotly, matlab.engine"],
+        stderr=subprocess.DEVNULL) == 0:
+    import plotly
+    import matlab.engine
+    from matlab.engine import EngineError, MatlabExecutionError
+elif subprocess.call(
+        [sys.executable, "-c", "import matlab.engine, plotly"],
+        stderr=subprocess.DEVNULL) == 0:
+    import matlab.engine
+    from matlab.engine import EngineError, MatlabExecutionError
+    import plotly
+else:
+    import matlab.engine
+    from matlab.engine import EngineError, MatlabExecutionError
+    plotly = None
+    warnings.warn(
+        "Failed to import both matlab.engine and plotly in the same process; "
+        "plotly output is unavailable.")
```

i.e. try to import both matlab.engine and plotly in a subprocess in either order, and check what order works.

If one of you can confirm that this fixes a previously present problem (on the same install) then I'll push the fix.

**Comment by rkdarst** [comment]
If you can give me the commit, I am happy to try it out.  But like I said, apparently the original problem doesn't occur for me with `imatlab`.

**Comment by anntzer** [comment]
Would rather have someone who *does* have the original problem to try it :-)  If no one manifests themselves I'll just leave things as they are.

**Comment by anntzer** [comment]
Pushed the above fix.

**Comment by RoyiAvital** [comment]
@anntzer ,
I'm installing this on Linux Mint 18.3 (Ubunti 16.04 basically) with MATLAB R0218a.

When I run `python -mimatlab install` I get `[Errno 13] Permission denied: '/usr/local/share/jupyter'`.

Could it use the local user Jupyter configuration files?
I don't have root permission.
