### ISSUE TITLE
pip git installation does not put resources folder imatlab folder in site-packages

### ISSUE THREAD

**Issue by linussun** [imatlab/imatlab#34]
Discovered this when trying to use imatlab_export_fig('') to set native vs PNG vs JPG plotting - received a command not found type error....

Plotly integration also not working at moment either. Only see "Drawing..." dialog and missing figure in notebook.  This error occurs with Anaconda3 install or miniconda3 install, after jupyter is installed, Matlab engine installed and then using python -mpip install git+https://github.com/imatlab/imatlab (from Github); then run python -mimatlab install.

My system Mac OS X Sierra 10.13.3.

**Comment by anntzer** [comment]
Indeed, found the bug.  Should be fixed now, please confirm it works for you.

**Comment by linussun** [comment]
Confirmed! Thanks!
