### ISSUE TITLE
The installation command does not work with R2017b

### ISSUE THREAD

**Issue by r91522831** [imatlab/imatlab#40]
Get the message below after running the install command: python -mpip install imatlab
--
Collecting imatlab
  Using cached imatlab-0.3-py3-none-any.whl
Requirement already satisfied: widgetsnbextension>=1.0 in /Applications/anaconda/lib/python3.6/site-packages (from imatlab)
Collecting plotly>=1.13.0 (from imatlab)
  Using cached plotly-2.5.1.tar.gz
Collecting matlabengineforpython>=R2016b (from imatlab)
  Could not find a version that satisfies the requirement matlabengineforpython>=R2016b (from imatlab) (from versions: )
No matching distribution found for matlabengineforpython>=R2016b (from imatlab)

I have python 3.6 and Matlab R2017b. Is there a way to fix the issue?

**Comment by r91522831** [comment]
Sorry, it worked. I install the engine in the wrong version.

**Comment by RoyiAvital** [comment]
I have the same error while it is installed (From MATLAB R2018a).
How can I tell `imatlab` where is it installed?

**Comment by anntzer** [comment]
How did you install matlabengineforpython?

**Comment by RoyiAvital** [comment]
The funny thing is the kernel works (The previous installation, I'm just trying to reinstall to make sure I have the latest version).

I installed it as always (Into user defined location).

**Comment by anntzer** [comment]
As already mentioned in other threads, nonstandard installs are not supported.  Yes it is possible to make things work but I have no intent of transforming this bug tracker into a pip tutorial.

**Comment by RoyiAvital** [comment]
Everything works.
The Kernel itself in Jupyter works and find the MATLAB Python Engine.
The installation (To make sure it is the latest) suddenly doesn't.

If I reinstall the MATLAB Engine (Again, in non standard place) all works again.
It's like the installer forgets where it is.

Regarding no support for special places.
Well, your installation instructions support installation for users without Administrator privileges (Using the `--user` flag).
Yet you require installing the MATLAB Python Engine in its default location which requires Administrator privileges.
It seems like it kind of misses the point, doesn't it?

Could you have instructions how to explicitly tel `pip` and Kernels where is the MATLAB Python Engine?

This is exactly why a Wiki is needed.

**Comment by anntzer** [comment]
See, once again, https://github.com/imatlab/imatlab/issues/2#issuecomment-375077709.
This bug tracker is not a pip tutorial.  Please refrain from further queries on the same topic.

**Comment by RoyiAvital** [comment]
It has nothing to so with `pip` tutorial.
Again, you support User Level installation of `imatlab`.
How could one set a User Level installation of `imatlab` with a User Level installation of MATLAB Python Engine?

We need consistency here.
