### ISSUE TITLE
Interactive function definition question.

### ISSUE THREAD

**Issue by Carreau** [imatlab/imatlab#41]
Hey,

I recently (yesterday) install ed imatlab to someone used to matlab and stating to use Jupyter. I got falbbergasted that you can't interactively define function – which did not appear to perturbe the person I was installing that for. 

I was still wondering if I was missing something, and that with this kernel you can still define function interactively. If not I'm fine, but was wondering if it's something that has been considered. 

Just asking this out of curiosity as I see interactive function definition as a core component in the notebook workflow.

**Comment by anntzer** [comment]
Nah, MATLAB is just as terrible a language as you'd expect.  See https://github.com/Calysto/matlab_kernel/issues/69 for some options though.
Closing as "upstream bug" :-); would probably accept a PR implementing https://github.com/Calysto/matlab_kernel/issues/69#issuecomment-257810123.

**Comment by Carreau** [comment]
Fair enough. I tried to install the Calysto one but failed, and anyway that's for moving someone from Python to Matlab, so it's only to execute existing scripts.

Thanks!

**Comment by Carreau** [comment]
> from Python to Matlab

Gniaaa no, the opposite. From Matlab to Python :-)

**Comment by anntzer** [comment]
My lab has too big a codebase in MATLAB so I can't avoid using it sometimes, but at least this kernel gives me a ptk interface :-) (which already is a big improvement...)

**Comment by Carreau** [comment]
> My lab has too big a codebase in MATLAB so I can't avoid using it sometimes, but at least this kernel gives me a ptk interface :-) (which already is a big improvement...)

Using `Jupyter console` ?  Do you experience Ctrl-D/exit not killing the kernel if it is owned by the console ? I know some R people do.

**Comment by anntzer** [comment]
With jupyter console indeed, I actually nearly never use the notebook (whether for Python or MATLAB).
Quitting works fine for me (https://github.com/imatlab/imatlab/blob/master/lib/imatlab/_kernel.py#L398) although #32 may be relevant (I haven't really looked into it as it doesn't affect me).
