### ISSUE TITLE
Magics support

### ISSUE THREAD

**Issue by JanGrohn** [imatlab/imatlab#43]
Is there any particular reason why there is no magics system? Working around the MATLAB issue of defining functions in separate files as described here https://stackoverflow.com/questions/48653873/how-to-write-matlab-functions-in-jupyter-notebook for the Calysto kernal would be a nice addition.

**Comment by anntzer** [comment]
See https://github.com/Calysto/matlab_kernel/pull/72#issuecomment-268877631 for why I this kernel does not (and will not) implement magics.
See https://github.com/Calysto/matlab_kernel/issues/69 for ideas regarding function support.
