### ISSUE TITLE
function cannot define in jupyter notebook

### ISSUE THREAD

**Issue by jishin86** [imatlab/imatlab#49]
Hello, 
I'm very new about matlab.

In matlab, To execute a user-defined function, I heard that the user must define function in script file or function *.m file.

Even if imatlab is not support magic %% , some guideline suggest to define function in jupyter.

https://am111.readthedocs.io/en/latest/jmatlab_use.html#Standard-functions

In my trial, I must make new notebook on python kernel,  write func.m file with %%file magic and call the function from new notebook on matlab kernel. 
In the matlab notebook,  %%file was not working because imatlab does not support the magics system.

Could you give a tip instead of my way?

Thanks

ps. I used ubuntu18, anaconda3, python 3.6, matlab 2018a. And I also test the same with python 3.5 .

**Comment by anntzer** [comment]
The documentation you link is for https://github.com/Calysto/matlab_kernel/, which is a different kernel from this one.
imatlab does not support magics.
