### ISSUE TITLE
Error in R2019a, matlabengineforpython>=R2016b, default path. 

### ISSUE THREAD

**Issue by kevinjohncutler** [imatlab/imatlab#55]
On Ubunu 18.04 running Matlab R2019a. I am trying to run `pip install imatlab` and get the error

`Could not find a version that satisfies the requirement matlabengineforpython>=R2016b (from imatlab) (from versions: )
No matching distribution found for matlabengineforpython>=R2016b (from imatlab)`

I have created a conda environment with python 3.6 and used `pyversion` to change Matlab's default python version to 3.6. All the code is running in this environment and I have already run `python setup.py install` in the _default_ folder /usr/local/MATLAB/R2019a/extern/engine. This is probably an issue on my end rather than an issue with imatlab, but it could be useful for others if someone could help me sort it out. 

Thanks in advance.

**Comment by anntzer** [comment]
Can you `import matlab.engine`?  If yes, what's `matlab.__file__`?  Does `matlabengineforpython` show up in `pip list`?

Note that `pyversion` doesn't really matter here, it sets the version of Python used by MATLAB but we want to use MATLAB from Python.

**Comment by kevinjohncutler** [comment]
> 
> 
> Can you `import matlab.engine`? If yes, what's `matlab.__file__`? Does `matlabengineforpython` show up in `pip list`?
> 
> Note that `pyversion` doesn't really matter here, it sets the version of Python used by MATLAB but we want to use MATLAB from Python.

Thanks for replying so quickly - I tried again this morning with `sudo pip install imatlab` and it ran without errors. I ran the `python setup.py install` again and then `pip list`, but `matlabengineforpython` is not there. The command `import matlab.engine` gives me a permission error, though `sudo import matlab.engine` runs with no output - where would I find `matlab.__file__`? (I think I understand that `_file_` would be some specific name).

**Comment by anntzer** [comment]
As a general rule: never, ever use `sudo pip` (I'll let you google for why).
Not sure what is the state of your system right now but I guess you may be able to get away with something like
```sh
pip uninstall imatlab  # may need sudo, to undo earlier install
pip uninstall matlabengineforpython  # may need sudo, may or may not succeed
```
then, from the matlab engine directory
```
python setup.py install --user
```
(may need to set --build-base per https://www.mathworks.com/help/matlab/matlab_external/install-matlab-engine-api-for-python-in-nondefault-locations.html to e.g. /tmp)

then try (e.g. from $HOME) `import matlab.engine; print(matlab.__file__)`.
if that works
```
pip install --user imatlab
```
or even
```
pip install --user --no-deps imatlab
```
if you're feeling lucky.

**Comment by anntzer** [comment]
I think there is no specific issue on imatlab's side to be handled here(?), so closing.

**Comment by kevinjohncutler** [comment]
That's probably right, but it might be helpful to lay out what users should be doing on their end to set up imatlab. What I found is that `imatlab` and `matlabengineforpython` install properly _only if I am root__, but not as a user with root privileges. Not sure how to fix that yet.

**Comment by anntzer** [comment]
First, you need to get matlabengineforpython properly installed *without being root*; i.e., you need to be able to do `from matlab import engine; engine.start_matlab()` from a regular (non-root) python console.  This part is independent of imatlab and I cannot help you much there (other than the suggestions above).  If you cannot make this work, I would suggest looking for help through MATLAB support.

*Assuming the above works*, what happens if you do `pip install imatlab --user; python -mimatlab install --user`?

**Comment by kevinjohncutler** [comment]
I can't seem to get `python setup.py install` to work at all. The `--user` flag gives me `error: You do not have write permission in build/lib/matlab/engine/ `, while `sudo` makes it run but it does not show up in `pip list`. I think installing with sudo is making it invisible. Clearly this is an issue on my end.

**Comment by kevinjohncutler** [comment]
Just in case anybody has the same issue I have: clearly there is a permissions error that does not allow me to install the packages, so I had to use sudo. However, sudo changes something about the installation path and evern the version of python. Instead of `python setup.py install`, used `sudo <path given by which python> setup.py install` in my anaconda environment. It also works to use `sudo chown` ont he relevant directory, but there are some security concerns when editing filesystem permissions like that. 

After this everything installed correctly - please let me (and others) know if there is anything I did here that can and should be avoided.
