### ISSUE TITLE
Multiple figures rendering error, only last figure repeated for n figures.

### ISSUE THREAD

**Issue by linussun** [imatlab/imatlab#58]
I thought I saw this somewhere else but can't find it now.

When plotting and exporting multiple figures (imatlab_export_fig('print-png')) in one cell, only the last figure is repeated for the number of figures I want. So if plot figure 1,2,3,4,5, the output shows figures 5,5,5,5,5. 

Running 2018b (update 4) and latest Jupyter lab (0.35.4).

Thanks
![Capture3](https://user-images.githubusercontent.com/6187350/60736055-b15f5f00-9f23-11e9-900f-5c5a916518be.PNG)

**Comment by anntzer** [comment]
woops.  should be fixed now, give it a try?

**Comment by linussun** [comment]
Works now, thanks!
