### ISSUE TITLE
Empty stderr output creates light red box below each executed code cell

### ISSUE THREAD

**Issue by pierre-haessig** [imatlab/imatlab#60]
Dear imatlab maintainers,

It's my first usage of imatlab (thanks for creating it!). I've noticed a minor display issue. For every executed Matlab code cell, I get an empty light red (i.e. pink) box below the regular (white) output box. I'm on Jupyterlab 1.1.4 with Firefox 69. Here is an example:

![screenshot of executed cell with red box below](https://user-images.githubusercontent.com/1010404/67713324-e8231e80-f9c5-11e9-8403-fd85c475222b.png)

I've looked at the notebook JSON source code. It seems that the cell execution creates two output objects. The first has its `name` attribute set to `stdout` while the second is `stderr`. I guess this is the one which renders as a light red box, although it's `text` attribute is an empty list.

Is it an imatlab issue (like the errouneous inclusion of an empty stderr output) or a Jupyterlab rendering issue (like rendering a box for an empty output) ?

Here is the JSON code of the Notebook cell corresponding to the screenshot:
```
{
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": []
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": []
    }
   ],
   "source": [
    "imatlab_export_fig('print-png')  % Static png figures.\n",
    "%imatlab_export_fig('')  % Native windows."
   ]
  }
```

**Comment by anntzer** [comment]
I can't repro with Jupyterlab 1.1.4 + imatlab master + chromium 78:
![Screenshot_20191028_231302](https://user-images.githubusercontent.com/1322974/67722116-9afc7800-f9d8-11e9-8473-09f66b73cfd9.png)
or + firefox 70.

**Comment by pierre-haessig** [comment]
And what about the notebook JSON code ?

Oh, and I forgot to mention I'm on Matlab R2018b on Windows.

**Comment by pierre-haessig** [comment]
Should I switch to master?

**Comment by anntzer** [comment]
Actually, are you on Windows?
If so, does
```patch
diff --git i/lib/imatlab/_kernel.py w/lib/imatlab/_kernel.py
index 7117516..f685aaa 100644
--- i/lib/imatlab/_kernel.py
+++ w/lib/imatlab/_kernel.py
@@ -232,7 +232,9 @@ class MatlabKernel(Kernel):
                 status = "error"
             finally:
                 for name, buf in [("stdout", out), ("stderr", err)]:
-                    self._send_stream(name, buf.getvalue())
+                    v = buf.getvalue()
+                    if v:
+                        self._send_stream(name, v)
         else:
             raise OSError("Unsupported OS")
```
help?

**Comment by pierre-haessig** [comment]
Thanks for the patch, it works!

**Comment by anntzer** [comment]
pushed the fix
