### ISSUE TITLE
Tab completion broken for Matlab version >2020

### ISSUE THREAD

**Issue by hugke729** [imatlab/imatlab#64]
Matlab 2020a removed `com.mathworks.jmi.MatlabMCR().mtGetCompletions` ([see here](https://github.com/Gimly/vscode-matlab/issues/110#issuecomment-604635781))

Consequently, tab completion no longer works in iMatlab and causes kernel to crash.

There is a similar function available instead:

`com.mathworks.jmi.MatlabMCR().mtFindAllTabCompletions(string_in, len(string_in), 0)`

The output of this is a list, not a JSON object as it is for mtGetCompletions.

I tried swapping these two functions in `do_complete()` in `_kernel.py`, but couldn't get it to work.

Here's my attempt:
```python
def do_complete(self, code, cursor_pos):                                                                                                                                                                       
    info_s = self._call(
        "eval",
        "cell(com.mathworks.jmi.MatlabMCR().mtFindAllTabCompletions('{}', {}, 0))"
        .format(code[:cursor_pos], cursor_pos)
    return {"cursor_start": 0, "cursor_end": cursor_pos,
            "matches": info_s, "metadata": None, "status": "ok"}
```
where the metadata and status keys are failed attempts to avoid errors telling me that those keys are missing. I'm not sure if they're needed or what they should be.

I'm using Matlab R2022b and python 3.9

I'll play around with this more when I have more time and report back if I get anywhere.

**Comment by hugke729** [comment]
For now, I've commented out the `do_complete` function to stop the kernel from crashing if I hit <Tab>.

For anyone trying this out, remember to delete the `__pycache__` directory in `site-packages/imatlab` after making changes to `_kernel.py`

**Comment by anntzer** [comment]
Thanks for the report, this should hopefully be fixed now as of master.
