### ISSUE TITLE
End of Support - Reconsider?

### ISSUE THREAD

**Issue by RoyiAvital** [imatlab/imatlab#67]
Hi,

Your kernel is much better than anything else out there.
Is there a chance you reconsider your end of support?

What you accomplished here is brilliant.

**Comment by anntzer** [comment]
You are welcome to fork the repo and restart work on it :)

**Comment by RoyiAvital** [comment]
I wish I had a clue.

Anyhow, at least I had the opportunity to say your work is appreciated.

**Comment by anntzer** [comment]
Thank you, the kind words are well appreciated.
